name: docker-compose-app
include:
  - notebooks-backend/compose.yaml
  - notes-backend/compose.yaml

services:
  reverse-proxy:
    image: nginx:1.27.0
    volumes:
      - type: bind
        source: ./reverse-proxy/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "5000:80"
    networks:
      - notes-app-network
    depends_on:
      - notebooks
      - notes

networks:
  notes-app-network:
