name: notes-app
include:
  - notebooks-backend/compose.yaml
  - notes-backend/compose.yaml

services:
  reverse-proxy:
    image: nginx:1.27.0
    volumes:
      - type: bind
        source: ./reverse-proxy/nginx.conf
        target: /etc/nginx/nginx.conf
        readonly: true
    ports:
      - "8080:80"
    depends_on:
      - notebooks
      - notes