apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    app.kubernetes.io/name: traffic-generator
spec:
  containers:
  - name: traffic-generator
    image: felipefabiani/traffic-gen:1.0.0
    args:
      - "color-api-svc/api"
      - "0.5"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

