apiVersion: v1
kind: Pod
metadata:
  name: heavy-api
  namespace: dev
  labels:
    app: heavy-api
spec:
  containers:
  - name: heavy-api
    image: felipefabiani/color-api:1.1.0
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: heavy-api-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: heavy-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80