apiVersion: v1
kind: Namespace 
metadata:
  name: prod

---
apiVersion: v1  
kind: ResourceQuota
metadata:
  namespace: prod
  name: prod-quota
spec:
  hard:
    requests.cpu: "2" # "equals to 2000m"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi