name: notes-backend
services:
  notes:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:80"
    environment:
      - PORT=80
      - DB_URL=mongodb://${NOTES_DB_USER}:${NOTES_DB_PASSWORD}@notes-db/${NOTES_DB_NAME}
    networks:
      - notes-net
    develop:
      watch: 
        - action: sync
          path: ./src
          target: /app/src
  notes-db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      # - './db-config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      - type: volume
        source: notes-data
        target: /data/db
    networks:
      - notes-net

volumes:
  notes-data:

networks:
  notes-net: